import { FeaturedCompanies, LatestPosts, Navbar, RecommendedJobs, Schedule, Title } from "components";
import Head from "next/head";
import { useEffect, useState } from "react";
import { useSelector, useDispatch } from "react-redux";
import { update } from '../redux/isMobileSlice'

export default function Home() {
  const isMobile = useSelector(state => state.isMobile.value)
  const isDark = useSelector(state => state.darkMode.value)
  const dispatch = useDispatch()

  useEffect(() => {
    const checkSize = () => {
      if (window.innerWidth <= 768) {
        dispatch(update(true))
      } else {
        dispatch(update(false))
      }
    }

    window.addEventListener('resize', checkSize)

    checkSize()

    return () => {
      window.removeEventListener('resize', checkSize)
    }
  }, [])
  return (
    <>
      <Head>
        <title>Jobit</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navbar />
        <div className={`${!isDark ? 'bg-[#FAFAFB]' : 'bg-[#13131A]'} px-6 h-full py-20`}>
          <Title title='Welcome to the Job Search Platform for Developers' />
          <LatestPosts />
          <FeaturedCompanies />
          <RecommendedJobs />
          <Schedule />
        </div>
      </main>
    </>
  )
}
