import { FeaturedCompanies, LatestPosts, Loader, Navbar, RecommendedJobs, Schedule, Title } from "components";
import Head from "next/head";
import { useSelector, useDispatch } from "react-redux";
import { useEffect } from "react";

import { update } from "redux/apiDataSlice";

export default function Home() {
  const isDark = useSelector(state => state.darkMode.value)
  const apiData = useSelector(state => state.apiData.value)
  const dispatch = useDispatch()

  const options = {
    method: 'GET',
    headers: {
      'X-RapidAPI-Key': 'KJwZZIJSFimshuivMSVGaiYzkRomp15f2vKjsnK4bKzuUzVLzA',
      'X-RapidAPI-Host': 'jsearch.p.rapidapi.com'
    }
  };

  console.log(apiData, 'apiData')

  const fetchData = async () => {
    navigator.geolocation.getCurrentPosition((position) => {
      console.log(position, 'position')
      const geoApiUrl = `https://api.bigdatacloud.net/data/reverse-geocode-client?latitude=${position.coords.latitude}&longitude=${position.coords.longitude}&localityLanguage=en`;

      fetch(geoApiUrl)
        .then(response => response.json())
        .then(data => {
          console.log(data, 'data')
          fetch(`https://jsearch.p.rapidapi.com/search?query=React%20developer%20in%20${data?.city}&num_pages=2`, options)
            .then(response => response.json())
            .then(response => {
              dispatch(update(response.data))
              return
            })
            .catch(err => console.error(err));
        })
    });

    fetch(`https://jsearch.p.rapidapi.com/search?query=React%20developer%20in%20New%20York&num_pages=2`, options)
      .then(response => response.json())
      .then(response => {
        dispatch(update(response.data))
        return
      })
      .catch(err => console.error(err));
  }

  useEffect(() => {
    fetchData()
  }, [])

  if (apiData?.length === 0 || !apiData) return (<div className="h-screen w-full items-center justify-center flex"><Loader /></div>)

  return (
    <>
      <Head>
        <title>Jobit</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className={`${!isDark ? 'bg-[#FAFAFB]' : 'bg-[#13131A]'} h-full py-20 px-6 md:px-20`}>
          <Title title='Welcome to the Job Search Platform for Developers' />
          <div className='md:flex md:gap-10'>
            <div className='md:flex md:flex-col md:w-[60%]'>
              <LatestPosts />
              <FeaturedCompanies />
            </div>
            <div className='md:flex md:flex-col md:w-[40%]'>
              <RecommendedJobs />
            </div>
          </div>
          <div className="block md:hidden">
            <Schedule />
          </div>
        </div>
      </main>
    </>
  )
}
